from django.urls import include, path

from .api import (
    AddonsSummaryApiView,
    DashboardSummaryApiView,
    InboxBulkRetryApiView,
    InboxItemRetryApiView,
    InboxRecentApiView,
    KpiSummaryApiView,
    RecentAlertsApiView,
    SecurityAddonDetailApiView,
    SecurityAddonsApiView,
    SecurityHealthApiView,
    SecuritySessionApiView,
    router,
)
from .api_ai import (
    AIChatApiView,
    AIAnalyzeReportApiView,
    AISuggestAlertRuleApiView,
    AIAnalyzeEventsApiView,
    AIGenerateSummaryApiView,
    AIUsageSummaryApiView,
    AIProviderStatusApiView,
    AIOperationsSummaryApiView,
    AIConfigurationCopilotApiView,
    AIConfigurationContextPreviewApiView,
    AIContextPreviewApiView,
    AIMemoryIndexApiView,
    AIMemoryFactsApiView,
    AIExplainAlertApiView,
    AISummarizeEvidenceApiView,
    AIRemediationPlanApiView,
)
from .api_configuration import (
    ConfigurationOverviewApiView,
    ConfigurationSourcesApiView,
    ConfigurationRulesApiView,
    ConfigurationNotificationsApiView,
    ConfigurationSuppressionsApiView,
    ConfigurationTestApiView,
    ConfigurationSourcePresetsApiView,
    ConfigurationSourceCreateApiView,
    ConfigurationSourceUpdateApiView,
    ConfigurationSourceToggleApiView,
    ConfigurationSourceIngestApiView,
    ConfigurationRuleSimulateApiView,
    MailboxIngestionServiceStatusApiView,
    MailboxIngestionServiceRunApiView,
    GraphSettingsApiView,
    LoginApiView,
    LogoutApiView,
    UsersListApiView,
    UserDetailApiView,
    GroupsListApiView,
    GroupDetailApiView,
)
from . import views


app_name = "security"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("security/", views.dashboard, name="security_dashboard"),
    path("security/alerts/", views.alerts_list, name="alerts_list"),
    path("security/alerts/<int:pk>/", views.alert_detail, name="alert_detail"),
    path("security/alerts/<int:pk>/actions/<slug:action>/", views.alert_action, name="alert_action"),
    path("security/tickets/", views.tickets_list, name="tickets_list"),
    path("security/inbox/", views.inbox_page, name="inbox"),
    path("security/kpis/", views.kpis_page, name="kpis"),
    path("security/pipeline/", views.pipeline_page, name="pipeline"),
    path("security/help/", views.help_page, name="help"),
    path("security/pipeline/run/<slug:action>/", views.pipeline_run, name="pipeline_run"),
    path("security/admin/config/", views.admin_config_dashboard, name="admin_config"),
    path("security/admin/config/general/", views.admin_config_general, name="admin_config_general"),
    path("security/admin/config/sources/", views.admin_config_sources, name="admin_config_sources"),
    path("security/admin/config/parsers/", views.admin_config_parsers, name="admin_config_parsers"),
    path("security/admin/config/alert-rules/", views.admin_config_alert_rules, name="admin_config_alert_rules"),
    path("security/admin/config/suppressions/", views.admin_config_suppressions, name="admin_config_suppressions"),
    path("security/admin/config/backups/", views.admin_config_backups, name="admin_config_backups"),
    path("security/admin/config/notifications/", views.admin_config_notifications, name="admin_config_notifications"),
    path("security/admin/config/ticketing/", views.admin_config_ticketing, name="admin_config_ticketing"),
    path("security/admin/config/audit/", views.admin_config_audit, name="admin_config_audit"),
    path("security/admin/diagnostics/", views.admin_diagnostics, name="admin_diagnostics"),
    path("security/admin/docs/", views.admin_docs, name="admin_docs"),
    path("security/admin/addons/", views.admin_addons, name="admin_addons"),
    path("security/admin/addons/<slug:code>/", views.admin_addon_detail, name="admin_addon_detail"),
    path("security/api/dashboard-summary/", DashboardSummaryApiView.as_view(), name="api_dashboard_summary"),
    path("security/api/alerts/recent/", RecentAlertsApiView.as_view(), name="api_alerts_recent"),
    path("security/api/inbox/recent/", InboxRecentApiView.as_view(), name="api_inbox_recent"),
    path("security/api/inbox/<slug:item_kind>/<int:pk>/retry/", InboxItemRetryApiView.as_view(), name="api_inbox_item_retry"),
    path("security/api/inbox/bulk-retry/", InboxBulkRetryApiView.as_view(), name="api_inbox_bulk_retry"),
    path("security/api/kpis/summary/", KpiSummaryApiView.as_view(), name="api_kpis_summary"),
    path("security/api/addons/summary/", AddonsSummaryApiView.as_view(), name="api_addons_summary"),
    path("api/security/health/", SecurityHealthApiView.as_view(), name="api_security_health"),
    path("api/security/session/", SecuritySessionApiView.as_view(), name="api_security_session"),
    path("api/security/addons/", SecurityAddonsApiView.as_view(), name="api_addons"),
    path("api/security/addons/<slug:code>/", SecurityAddonDetailApiView.as_view(), name="api_addon_detail"),
    path("security/api/configuration/overview/", ConfigurationOverviewApiView.as_view(), name="api_configuration_overview"),
    path("security/api/configuration/sources/", ConfigurationSourcesApiView.as_view(), name="api_configuration_sources"),
    path("security/api/configuration/source-presets/", ConfigurationSourcePresetsApiView.as_view(), name="api_configuration_source_presets"),
    path("security/api/configuration/sources/create/", ConfigurationSourceCreateApiView.as_view(), name="api_configuration_source_create"),
    path("security/api/configuration/sources/<slug:code>/", ConfigurationSourceUpdateApiView.as_view(), name="api_configuration_source_update"),
    path("security/api/configuration/sources/<slug:code>/toggle/", ConfigurationSourceToggleApiView.as_view(), name="api_configuration_source_toggle"),
    path("security/api/configuration/sources/<slug:code>/ingest/", ConfigurationSourceIngestApiView.as_view(), name="api_configuration_source_ingest"),
    path("security/api/configuration/graph/settings/", GraphSettingsApiView.as_view(), name="api_configuration_graph_settings"),
    path("security/api/services/mailbox-ingestion/status/", MailboxIngestionServiceStatusApiView.as_view(), name="api_mailbox_ingestion_service_status"),
    path("security/api/services/mailbox-ingestion/run/", MailboxIngestionServiceRunApiView.as_view(), name="api_mailbox_ingestion_service_run"),
    path("security/api/configuration/rules/", ConfigurationRulesApiView.as_view(), name="api_configuration_rules"),
    path("security/api/configuration/rules/simulate/", ConfigurationRuleSimulateApiView.as_view(), name="api_configuration_rules_simulate"),
    path("security/api/configuration/notifications/", ConfigurationNotificationsApiView.as_view(), name="api_configuration_notifications"),
    path("security/api/configuration/suppressions/", ConfigurationSuppressionsApiView.as_view(), name="api_configuration_suppressions"),
    path("security/api/configuration/test/", ConfigurationTestApiView.as_view(), name="api_configuration_test"),
    path("api/security/auth/login/", LoginApiView.as_view(), name="api_auth_login"),
    path("api/security/auth/logout/", LogoutApiView.as_view(), name="api_auth_logout"),
    path("api/security/users/", UsersListApiView.as_view(), name="api_users_list"),
    path("api/security/users/<int:user_id>/", UserDetailApiView.as_view(), name="api_user_detail"),
    path("api/security/groups/", GroupsListApiView.as_view(), name="api_groups_list"),
    path("api/security/groups/<int:group_id>/", GroupDetailApiView.as_view(), name="api_group_detail"),
    path("api/security/ai/chat/", AIChatApiView.as_view(), name="api_ai_chat"),
    path("api/security/ai/analyze-report/", AIAnalyzeReportApiView.as_view(), name="api_ai_analyze_report"),
    path("api/security/ai/suggest-alert-rule/", AISuggestAlertRuleApiView.as_view(), name="api_ai_suggest_alert_rule"),
    path("api/security/ai/analyze-events/", AIAnalyzeEventsApiView.as_view(), name="api_ai_analyze_events"),
    path("api/security/ai/generate-summary/", AIGenerateSummaryApiView.as_view(), name="api_ai_generate_summary"),
    path("api/security/ai/usage-summary/", AIUsageSummaryApiView.as_view(), name="api_ai_usage_summary"),
    path("api/security/ai/provider-status/", AIProviderStatusApiView.as_view(), name="api_ai_provider_status"),
    path("api/security/ai/operations-summary/", AIOperationsSummaryApiView.as_view(), name="api_ai_operations_summary"),
    path("api/security/ai/configuration-copilot/", AIConfigurationCopilotApiView.as_view(), name="api_ai_configuration_copilot"),
    path("api/security/ai/configuration-context-preview/", AIConfigurationContextPreviewApiView.as_view(), name="api_ai_configuration_context_preview"),
    path("api/security/ai/context-preview/", AIContextPreviewApiView.as_view(), name="api_ai_context_preview"),
    path("api/security/ai/memory/index/", AIMemoryIndexApiView.as_view(), name="api_ai_memory_index"),
    path("api/security/ai/memory/facts/", AIMemoryFactsApiView.as_view(), name="api_ai_memory_facts"),
    path("api/security/ai/explain-alert/", AIExplainAlertApiView.as_view(), name="api_ai_explain_alert"),
    path("api/security/ai/summarize-evidence/", AISummarizeEvidenceApiView.as_view(), name="api_ai_summarize_evidence"),
    path("api/security/ai/remediation-plan/", AIRemediationPlanApiView.as_view(), name="api_ai_remediation_plan"),
    path("security/api/ai/memory/index/", AIMemoryIndexApiView.as_view(), name="api_ai_memory_index_legacy"),
    path("security/api/ai/memory/facts/", AIMemoryFactsApiView.as_view(), name="api_ai_memory_facts_legacy"),
    path("security/api/ai/chat/", AIChatApiView.as_view(), name="api_ai_chat_legacy"),
    path("security/api/ai/explain-alert/", AIExplainAlertApiView.as_view(), name="api_ai_explain_alert_legacy"),
    path("security/api/ai/summarize-evidence/", AISummarizeEvidenceApiView.as_view(), name="api_ai_summarize_evidence_legacy"),
    path("security/api/ai/remediation-plan/", AIRemediationPlanApiView.as_view(), name="api_ai_remediation_plan_legacy"),
    path("api/", include(router.urls)),
]
