# Generated by Django 5.2.13 on 2026-04-26 20:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=80)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityMailboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=24)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=24)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('suppressed', models.BooleanField(db_index=True, default=False)),
                ('decision_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityasset')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('suppressed', 'Suppressed')], db_index=True, default='new', max_length=24)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('decision_trace', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='security.securityeventrecord')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvidenceContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=24)),
                ('decision_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_containers', to='security.securityalert')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('report_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('parser_name', models.CharField(max_length=160)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='parsed', max_length=24)),
                ('parsed_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mailbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitymailboxmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=80)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='security.securityevidencecontainer')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityeventrecord')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityreport')),
            ],
        ),
        migrations.AddField(
            model_name='securityeventrecord',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='security.securityreport'),
        ),
        migrations.CreateModel(
            name='SecuritySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('source_type', models.CharField(choices=[('email', 'Email'), ('pdf', 'PDF'), ('csv', 'CSV'), ('api', 'API'), ('manual', 'Manual')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'is_active'], name='security_se_source__03d8cb_idx')],
            },
        ),
        migrations.AddField(
            model_name='securityreport',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='security.securitysource'),
        ),
        migrations.CreateModel(
            name='SecurityRemediationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(blank=True, db_index=True, max_length=32)),
                ('affected_product', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=24)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='security.securityalert')),
                ('evidence', models.ManyToManyField(blank=True, related_name='tickets', to='security.securityevidencecontainer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.securitysource')),
            ],
        ),
        migrations.AddField(
            model_name='securitymailboxmessage',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_messages', to='security.securitysource'),
        ),
        migrations.CreateModel(
            name='SecurityKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysource')),
            ],
        ),
        migrations.AddField(
            model_name='securityevidencecontainer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.securitysource'),
        ),
        migrations.AddField(
            model_name='securityeventrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='security.securitysource'),
        ),
        migrations.AddField(
            model_name='securityasset',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysource'),
        ),
        migrations.CreateModel(
            name='SecurityAlertSuppressionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=24)),
                ('match_payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysource')),
            ],
        ),
        migrations.AddField(
            model_name='securityalert',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security.securitysource'),
        ),
        migrations.CreateModel(
            name='BackupJobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('protected_items', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityreport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.securitysource')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('email', 'Email'), ('pdf', 'PDF'), ('csv', 'CSV'), ('api', 'API'), ('manual', 'Manual')], max_length=32)),
                ('content', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=24)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='security.securitysource')),
            ],
        ),
        migrations.AddField(
            model_name='securityreport',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securitysourcefile'),
        ),
        migrations.CreateModel(
            name='SecurityVulnerabilityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(db_index=True, max_length=32)),
                ('affected_product', models.CharField(db_index=True, max_length=255)),
                ('cvss', models.FloatField(db_index=True)),
                ('exposed_devices', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=24)),
                ('dedup_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityasset')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.securityreport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.securitysource')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAlertActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('actor', models.CharField(default='system', max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='security.securityalert')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='security.securityremediationticket')),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'created_at'], name='security_se_action_d63f63_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='security.securityreport')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'created_at'], name='security_se_name_9c9e0c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='securityremediationticket',
            index=models.Index(fields=['source', 'cve', 'affected_product', 'status'], name='security_se_source__404600_idx'),
        ),
        migrations.AddIndex(
            model_name='securityremediationticket',
            index=models.Index(fields=['dedup_hash', 'status'], name='security_se_dedup_h_849c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='securitymailboxmessage',
            index=models.Index(fields=['source', 'received_at'], name='security_se_source__27b8c0_idx'),
        ),
        migrations.AddIndex(
            model_name='securitymailboxmessage',
            index=models.Index(fields=['source', 'fingerprint'], name='security_se_source__33c90f_idx'),
        ),
        migrations.AddIndex(
            model_name='securitykpisnapshot',
            index=models.Index(fields=['snapshot_date', 'name'], name='security_se_snapsho_4c56b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securitykpisnapshot',
            unique_together={('source', 'snapshot_date', 'name')},
        ),
        migrations.AddIndex(
            model_name='securityevidencecontainer',
            index=models.Index(fields=['source', 'status', 'created_at'], name='security_se_source__6cf555_idx'),
        ),
        migrations.AddIndex(
            model_name='securityeventrecord',
            index=models.Index(fields=['source', 'occurred_at'], name='security_se_source__dc7746_idx'),
        ),
        migrations.AddIndex(
            model_name='securityeventrecord',
            index=models.Index(fields=['severity', 'occurred_at'], name='security_se_severit_67ee94_idx'),
        ),
        migrations.AddIndex(
            model_name='securityeventrecord',
            index=models.Index(fields=['asset', 'occurred_at'], name='security_se_asset_i_6c6a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityeventrecord',
            index=models.Index(fields=['dedup_hash', 'event_type'], name='security_se_dedup_h_bb2489_idx'),
        ),
        migrations.AddIndex(
            model_name='securityasset',
            index=models.Index(fields=['hostname', 'asset_type'], name='security_se_hostnam_4e5a33_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityasset',
            unique_together={('source', 'hostname')},
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['source', 'severity', 'status'], name='security_se_source__bba89b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['dedup_hash', 'status'], name='security_se_dedup_h_8b421c_idx'),
        ),
        migrations.AddIndex(
            model_name='securitysourcefile',
            index=models.Index(fields=['source', 'uploaded_at'], name='security_se_source__be2611_idx'),
        ),
        migrations.AddIndex(
            model_name='securitysourcefile',
            index=models.Index(fields=['source', 'fingerprint'], name='security_se_source__7f4840_idx'),
        ),
        migrations.AddIndex(
            model_name='securityreport',
            index=models.Index(fields=['source', 'report_date'], name='security_se_source__6c4086_idx'),
        ),
        migrations.AddIndex(
            model_name='securityreport',
            index=models.Index(fields=['report_type', 'parse_status'], name='security_se_report__430342_idx'),
        ),
        migrations.AddIndex(
            model_name='securityvulnerabilityfinding',
            index=models.Index(fields=['source', 'cve', 'affected_product'], name='security_se_source__c7691c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityvulnerabilityfinding',
            index=models.Index(fields=['severity', 'status'], name='security_se_severit_6e37bc_idx'),
        ),
    ]
