# Generated by Django 5.2.13 on 2026-04-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('snoozed', 'Snoozed'), ('muted', 'Muted'), ('closed', 'Closed'), ('false_positive', 'False positive'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], db_index=True, default='new', max_length=24),
        ),
        migrations.AlterField(
            model_name='securityevidencecontainer',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('snoozed', 'Snoozed'), ('muted', 'Muted'), ('closed', 'Closed'), ('false_positive', 'False positive'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=24),
        ),
        migrations.AlterField(
            model_name='securityremediationticket',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('snoozed', 'Snoozed'), ('muted', 'Muted'), ('closed', 'Closed'), ('false_positive', 'False positive'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=24),
        ),
        migrations.AlterField(
            model_name='securityvulnerabilityfinding',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('snoozed', 'Snoozed'), ('muted', 'Muted'), ('closed', 'Closed'), ('false_positive', 'False positive'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed')], db_index=True, default='open', max_length=24),
        ),
    ]
