# Generated by Django 5.2.13 on 2026-04-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_securityalertsuppressionrule_conditions_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityMailboxSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('mock', 'Mock'), ('graph', 'Microsoft Graph'), ('imap', 'IMAP')], default='manual', max_length=32)),
                ('mailbox_address', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('sender_allowlist_text', models.TextField(blank=True)),
                ('subject_include_text', models.TextField(blank=True)),
                ('subject_exclude_text', models.TextField(blank=True)),
                ('body_include_text', models.TextField(blank=True)),
                ('attachment_extensions', models.CharField(blank=True, max_length=255)),
                ('max_messages_per_run', models.PositiveIntegerField(default=50)),
                ('mark_as_read_after_import', models.BooleanField(default=False)),
                ('process_attachments', models.BooleanField(default=True)),
                ('process_email_body', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'source_type'], name='security_se_enabled_8fe232_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityMailboxIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('imported_messages_count', models.PositiveIntegerField(default=0)),
                ('skipped_messages_count', models.PositiveIntegerField(default=0)),
                ('duplicate_messages_count', models.PositiveIntegerField(default=0)),
                ('imported_files_count', models.PositiveIntegerField(default=0)),
                ('processed_items_count', models.PositiveIntegerField(default=0)),
                ('generated_alerts_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='security.securitymailboxsource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'started_at'], name='security_se_source__ef6efd_idx'), models.Index(fields=['status', 'started_at'], name='security_se_status_87b0e3_idx')],
            },
        ),
    ]
