# Generated by Django 5.2.13 on 2026-05-06 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_securityaiinteractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('context_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('context_object_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='security.aiconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(db_index=True, max_length=80)),
                ('source_object_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_object_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['source_type', 'source_object_type'], name='security_ai_source__5d33a5_idx'), models.Index(fields=['source_object_type', 'source_object_id'], name='security_ai_source__f9c22c_idx'), models.Index(fields=['content_hash'], name='security_ai_content_460aa3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='security.aiknowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='AIMemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, default='global', max_length=80)),
                ('key', models.CharField(db_index=True, max_length=160)),
                ('value', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('confidence', models.FloatField(default=1.0)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('source_object_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_object_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope', 'category', 'key'],
                'indexes': [models.Index(fields=['scope', 'category', 'is_approved'], name='security_ai_scope_a0a70d_idx'), models.Index(fields=['source_object_type', 'source_object_id'], name='security_ai_source__be60db_idx')],
                'unique_together': {('scope', 'key', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'updated_at'], name='security_ai_user_id_507152_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['context_type', 'context_object_id'], name='security_ai_context_c081ad_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='security_ai_convers_604ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversationmessage',
            index=models.Index(fields=['role', 'created_at'], name='security_ai_role_66cbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='security_ai_documen_57daeb_idx'),
        ),
        migrations.AddIndex(
            model_name='aiknowledgechunk',
            index=models.Index(fields=['text_hash'], name='security_ai_text_ha_74d37e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiknowledgechunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
