# Generated by Django 5.2.13 on 2026-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_aiknowledgeembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymailboxsource',
            name='require_verified_sender',
            field=models.BooleanField(default=False, help_text='Accept a message only if the receiving mail system authenticated the sender (DKIM or SPF pass, no DMARC failure). Requires a provider that exposes the Authentication-Results header, e.g. Microsoft Graph. Fail-closed: messages without the header are rejected.'),
        ),
    ]
