# Generated by Django 5.2.13 on 2026-07-13 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_securitymailboxsource_require_verified_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_kind', models.CharField(db_index=True, max_length=32)),
                ('severity', models.CharField(blank=True, choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=24)),
                ('dedup_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('cooldown', 'Suppressed by cooldown')], db_index=True, max_length=16)),
                ('recipients_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='security.securityalert')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='security.securitynotificationchannel')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='security.securityremediationticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'dedup_hash', 'event_kind', 'created_at'], name='security_se_channel_62d7e5_idx'), models.Index(fields=['outcome', 'created_at'], name='security_se_outcome_5304f0_idx')],
            },
        ),
    ]
