# Generated by Django 5.2.13 on 2026-07-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_securitynotificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitymailboxsource',
            name='expected_every_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='How often a report is expected from this source, in hours (0 = no expectation). A source that goes quiet raises an alert: the absence of a report is itself a signal, and it is the one failure the system cannot see by looking at what arrives.'),
        ),
    ]
