from django.contrib import admin
from django.urls import include, path

from .react_app import react_app_view, react_asset_view


urlpatterns = [
    path("admin/", admin.site.urls),
    path("assets/<path:path>", react_asset_view, name="react_app_assets"),
    path("", react_app_view, name="react_app"),
    path("app/", react_app_view, name="react_app_app"),
    path("login", react_app_view, name="react_app_login"),
    path("login/", react_app_view, name="react_app_login_slash"),
    path("users", react_app_view, name="react_app_users"),
    path("users/", react_app_view, name="react_app_users_slash"),
    path("groups", react_app_view, name="react_app_groups"),
    path("groups/", react_app_view, name="react_app_groups_slash"),
    path("configuration", react_app_view, name="react_app_configuration"),
    path("configuration/", react_app_view, name="react_app_configuration_slash"),
    path("modules", react_app_view, name="react_app_modules"),
    path("modules/", react_app_view, name="react_app_modules_slash"),
    path("modules/<path:subpath>", react_app_view, name="react_app_module_route"),
    path("addons", react_app_view, name="react_app_addons"),
    path("addons/", react_app_view, name="react_app_addons_slash"),
    path("integrations/microsoft-graph", react_app_view, name="react_app_microsoft_graph"),
    path("integrations/microsoft-graph/", react_app_view, name="react_app_microsoft_graph_slash"),
    path("reports", react_app_view, name="react_app_reports"),
    path("reports/", react_app_view, name="react_app_reports_slash"),
    path("ai", react_app_view, name="react_app_ai"),
    path("ai/", react_app_view, name="react_app_ai_slash"),
    path("inbox", react_app_view, name="react_app_inbox"),
    path("inbox/", react_app_view, name="react_app_inbox_slash"),
    path("alerts", react_app_view, name="react_app_alerts"),
    path("alerts/", react_app_view, name="react_app_alerts_slash"),
    path("alerts/<path:subpath>", react_app_view, name="react_app_alerts_route"),
    path("assets", react_app_view, name="react_app_assets_page"),
    path("assets/", react_app_view, name="react_app_assets_page_slash"),
    path("services", react_app_view, name="react_app_services"),
    path("services/", react_app_view, name="react_app_services_slash"),
    path("evidence", react_app_view, name="react_app_evidence"),
    path("evidence/", react_app_view, name="react_app_evidence_slash"),
    path("rules", react_app_view, name="react_app_rules"),
    path("rules/", react_app_view, name="react_app_rules_slash"),
    path("", include("security.urls")),
]
